name: CI/CD Pipeline # Tên workflow (tùy chọn)

on: # Cấu hình trigger kích hoạt workflow
  push:
    branches: [ "master" ] # Kích hoạt khi push lên nhánh master
  pull_request:
    branches: [ "master" ] # Kích hoạt khi có pull request vào nhánh master

jobs: # Định nghĩa các job (công việc) trong workflow

  build-and-test-backend: # Job cho CI backend (Build và Test Backend)
    runs-on: ubuntu-latest # Chọn môi trường chạy job (Ubuntu)
    defaults: # Cấu hình thư mục làm việc mặc định
      run:
        working-directory: ./backend # Thư mục backend (nếu monorepo) hoặc "." nếu repo backend riêng

    steps: # Các bước thực hiện trong job build-and-test-backend
      - uses: actions/checkout@v3 # Checkout code từ repository

      - name: Set up JDK 17 # Cài đặt JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend with Maven # Build backend bằng Maven
        run: mvn clean install

      - name: Run Backend Tests # Chạy backend tests
        run: mvn test

      - name: Upload Backend Artifact # Upload JAR file backend làm artifact (để dùng cho deploy sau này)
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/target/*.jar # Đường dẫn đến file JAR

  build-frontend: # Job cho CI frontend (Build Frontend)
    runs-on: ubuntu-latest # Chọn môi trường chạy job (Ubuntu)
    defaults: # Cấu hình thư mục làm việc mặc định
      run:
        working-directory: ./frontend # Thư mục frontend (nếu monorepo) hoặc "." nếu repo frontend riêng

    steps: # Các bước thực hiện trong job build-frontend
      - uses: actions/checkout@v3 # Checkout code từ repository

      - name: Set up Node.js # Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Chọn phiên bản Node.js

      - name: Install Frontend Dependencies # Cài đặt dependencies frontend (npm install)
        run: npm install

      - name: Build Frontend # Build frontend (npm run build)
        run: npm run build

      - name: Upload Frontend Artifact # Upload build output frontend làm artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build # Đường dẫn đến thư mục build frontend

  deploy-backend: # Job cho CD backend (Deploy Backend)
    needs: build-and-test-backend # Job deploy backend phụ thuộc vào job build-and-test-backend thành công
    runs-on: ubuntu-latest

    steps: # Các bước thực hiện trong job deploy-backend
      - name: Download Backend Artifact # Download artifact backend đã build từ job trước
        uses: actions/download-artifact@v3
        with:
          name: backend-jar
          path: backend-deploy # Thư mục để download artifact backend

      - name: Deploy Backend # **[PLACEHOLDER] - Cấu hình deploy backend thực tế của bạn**
        run: |
          echo "Implement your backend deployment steps here..."
          # Ví dụ:
          # - SSH vào server backend
          # - Copy file JAR vào server
          # - Restart service backend
          # ...

  deploy-frontend: # Job cho CD frontend (Deploy Frontend)
    needs: build-frontend # Job deploy frontend phụ thuộc vào job build-frontend thành công
    runs-on: ubuntu-latest

    steps: # Các bước thực hiện trong job deploy-frontend
      - uses: actions/checkout@v3 # Checkout code

      - name: Download Frontend Artifact # Download artifact frontend đã build từ job trước
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: frontend-deploy # Thư mục để download artifact frontend

      - name: Deploy Frontend # **[PLACEHOLDER] - Cấu hình deploy frontend thực tế của bạn**
        run: |
          echo "Implement your frontend deployment steps here..."
          # Ví dụ deploy frontend lên GitHub Pages:
          # uses: actions/deploy-pages@v2
          # with:
          #   folder: frontend-deploy/build